spring:
  application:
    name: data-pipeline
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:postgresql://10.1.12.150:31432/paasdev
          username: paas
          password: Paas1234
        oracle-20:
          url: jdbc:oracle:thin:@10.1.8.15:1521:oracle12c
          username: paas2
          password: U%HYKs#n_3
pipeline:
  image: ${CONNECT_IMAGE:harbor.paas.nl:5000/paas_platform/debezium/connect:1.4.2.Final}
  namespace: ${CONNECT_NAME_SPACES:data-pipeline}
  configMapName: ${CONFIGMAP_NAME:data-pipeline-config}
