---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: paas-data-pipeline
  namespace: manage
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: paas-admin
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: paas-admin-binding
  namespace: manage
subjects:
  - kind: ServiceAccount
    name: paas-data-pipeline
    namespace: manage
roleRef:
  kind: ClusterRole
  name: paas-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: data-pipeline
  namespace: manage
spec:
  type: NodePort
  selector:
    app: data-pipeline
  ports:
  - name: data-pipeline-http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32110
  - name: cp-kafka-rest-http
    port: 8082
    protocol: TCP
    targetPort: 8082
    nodePort: 32211
  - name: burrow-http
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32212
  - name: kafdrop-http
    port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 32213
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-pipeline
  namespace: manage
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: data-pipeline
        track: stable
    spec:
      serviceAccountName: paas-data-pipeline
      containers:
      - name: data-pipeline
        image: harbor.paas.nl:5000/paas_platform/nl.paas.data-pipeline:2.3
        imagePullPolicy: Always
        env:
        - name: PF_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SPRING_PROFILES_ACTIVE
          value: dev93
        - name: JVM_OPTS
          value: "-XX:MaxRAMPercentage=70.0 -XX:InitialRAMPercentage=70.0 -XX:MinRAMPercentage=70.0"
        - name: LOG_PATH
          value: "/nl/paas/jdklogs"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: localpath
          mountPath: /nl/paas
      - name: cp-kafka-rest
        image: 10.1.8.15:5000/songdi/confluentinc/cp-kafka-rest:6.1.0
        imagePullPolicy: Always
        env:
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: 10.1.8.15:9092
        - name: KAFKA_REST_HOST_NAME
          value: rest-proxy
        - name: KAFKA_REST_LISTENERS
          value: http://0.0.0.0:8082
        ports:
        - containerPort: 8082
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: localpath
          mountPath: /nl/paas
      - name: burrow
        image: 10.1.8.15:5000/paas_platform/data-pipeline/burrow:1.3.6
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      - name: kafdrop
        image: 10.1.8.15:5000/songdi/kafdrop:3.27.0
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKERCONNECT
          value: 10.1.8.15:9092
        - name: SERVER_SERVLET_CONTEXTPATH
          value: /
        ports:
        - containerPort: 9000
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: localpath
        hostPath:
          path: /dcoslog/nl/paas
